wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 8000:80
  volumes:
    - ./wp-content/themes/save-science:/var/www/html/wp-content/themes/save-science

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
